packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/postcss': ^4.1.16
  autoprefixer: ^10.4.21
  next: ^16.0.0
  postcss: ^8.5.6
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^4.1.16
  typescript: ^5.9.3

ignoredBuiltDependencies:
  - unrs-resolver

nohoist:
  - '**/eslint'
  - '**/eslint-*'

onlyBuiltDependencies:
  - sharp
  - esbuild
  - turbo

packageExtensions:
  '@react-three/drei':
    peerDependencies:
      '@react-three/fiber': '*'
      react: '*'
      react-dom: '*'
      three: '*'
  '@react-three/fiber':
    peerDependencies:
      react: '*'
      react-dom: '*'
      three: '*'
